title: Susana Roman Garcia
description: PhD student on Computational Neuroscience and Ethics; MSc Neuroinformatics; BSc Neuroscience.// Estudiante de doctorado en Neurociencia Computacional y Ética; Maestría en Neuroinformática; Licenciada en Neurociencias.
  
theme: jekyll-theme-architect
